services:
  - type: web
    name: graziela-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
  - key: OPENAI_API_KEY
    value: ""
